### ISSUE TITLE
Halo doesn't follow animations and changes

### ISSUE THREAD

**Issue by mprinc** [mprinc/KnAllEdge#13]
+ If we change viewspec, or limitRange, halo will stay where it was before

+ Problem lies in the fact that halo is set at the MapLayout.nodeClicked
    + there it is created and positioned
+ We need to find a way to update it with every animation (by following MapView.update, or so)

**Comment by sinisarudan** [comment]
@mprinc I've reproduced the case when closing +/- a node with quite children that map is moved, with selected node coming out of focus and with Halo staying where it was.!

**Comment by mprinc** [comment]
Fixed with https://github.com/mprinc/KnAllEdge/commit/8e85f6aa4c39adfcb16d6fb0ee4d1cd1700ef8d2
