### ISSUE TITLE
right panel - overtaking space (EVEN for 'PROPERTIES', not just for 'Me')

### ISSUE THREAD

**Issue by sinisarudan** [mprinc/KnAllEdge#135]
We were aware after recent @mprinc's redesign of sidenav that right sidenav gets too-wide when we select its "Me' Tab, this is not so obtrusive and maybe even desired in most cases to gain more space for easier RIMA management.
**BUT** it happens also with 'Prop' tab, when it contains unbreakable text, like some long link, etc.
both are illustrated on images below.

**Possible solution** for the 'Prop' tab, by using the following CSS
```
word-wrap: break-word;
overflow-wrap: break-word;
word-break: break-all;
word-break: break-word;
```

![screen shot 2016-07-04 at 6 11 22 pm](https://cloud.githubusercontent.com/assets/1769627/16566336/b8f47af4-4213-11e6-8e93-febc60675ef2.png)

![screen shot 2016-07-04 at 6 18 52 pm](https://cloud.githubusercontent.com/assets/1769627/16566344/cd77dfd4-4213-11e6-9071-dd8034eb7958.png)

**Comment by mprinc** [comment]
I tried to fix it and set its width, but I didnt manage, I will try again
