### ISSUE TITLE
introduce BETA/sandbox/playground server

### ISSUE THREAD

**Issue by sinisarudan** [mprinc/KnAllEdge#152]
- so that **prod** should always have ONLY stable versions and to be used by our communities / users
- and Beta should be used for
 - beta users
 - our internal users
 - for testing colllaborative actions
 - for testing mobile version
 - etc

**Comment by mprinc** [comment]
Closed with [03e41e8](https://github.com/mprinc/KnAllEdge/commit/03e41e8883d7c6c11fb4861f1725cbc11af4e24d)

**Comment by mprinc** [comment]
We need to do the same with backend (and database?)
