### ISSUE TITLE
Rima-Ins - causes error

### ISSUE THREAD

**Issue by sinisarudan** [mprinc/KnAllEdge#172]
VIsualization / Components / Rima-Ins switch when changed, raises this error:
browser_adapter.ts:74 EXCEPTION: Error in http://localhost:5555/components/knalledgeMap/partials/tools.tpl.html:44:67
TypeError: self.context.toggleComponentView is not a function

Better to turn it off until fixed, not to cause errors for users 
@mprinc what is it used for anyway?

**Comment by mprinc** [comment]
@sinisarudan This seems to me is a set of switches for showing/hiding Components inside the tools sidenav. It is not implemented, idea was probably, that at one place we can control components. Probable we can hide it at the moment?

**Comment by sinisarudan** [comment]
@mprinc I don't need it
