### ISSUE TITLE
@angular/forms not accessed from the right direction

### ISSUE THREAD

**Issue by sinisarudan** [mprinc/KnAllEdge#175]
Adter installing new Angular forms
in package.json
```
"dependencies": {
"@angular/forms": "0.2.0",
}
```
we get error 
`(index):277 Error: (SystemJS) Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/@angular/forms.js`

So we had to copy that file from `@angular/forms/src/` to `@angular` ,as well as all other required files and folders, that we are subsequently warned about

This is strange because in DEMO-VERSION it is not required even though they don’t exist in 
https://angular.io/docs/ts/latest/guide/forms.html 

----

Maybe our settings are wrong, so we should direct the system to search for **forms** from
`http://localhost:5555/node_modules/@angular/forms/src/`
instead from
`http://localhost:5555/node_modules/@angular/`
we should say to the system (GULP or?) where to search for` @angular/form` as we do fo SystemJS _(that we don't use, btw)_
https://github.com/kara/material2/blob/8a1d36f7f1f88e4e840fe8d91b656c40e4bc4de5/GETTING_STARTED.md#configure-systemjs

> First, you need to let SystemJS know where to look when you import @angular2-material. You can do this by adding the path to the Material folder to the maps object.
> 
> src/system-config.ts
> 
> const map: any = {
>   '@angular2-material': 'vendor/@angular2-material'
> };
> This says something like "when you look for an @angular2-material import, look inside the vendor folder" (the base folder will already be dist).

**Comment by mprinc** [comment]
I think you just need to put it either in config file or in index.html
file, to set up path for SystemJS

**Comment by sinisarudan** [comment]
Yes, it was as we both suggested, issues of letting system know about it through SystemJS:

Closed by @mprinc with https://github.com/mprinc/KnAllEdge/commit/a5eff3a6c1abd82b862f8ae57f1faecae7eae1f5
