### ISSUE TITLE
Bottom Context-related Actions/Toolbar

### ISSUE THREAD

**Issue by sinisarudan** [mprinc/KnAllEdge#182]
@mprinc provide a **placeholder** a regular one that would be filled/injected with action icons etc, by active component(s)/puzzles,
like in this case: Brainstorming puzzle #139 .
It should be like bottom toolbar in **MCM** 

**TODO** 
- see how divide what goes in upper, what in lower toolbar.
- should be mobile-friendly

**Comment by mprinc** [comment]
OK, then this is my next task

**Comment by mprinc** [comment]
Implemented in a way that we send broadcasting message `showSubComponentInBottomPanelEvent` with the name of the pluggable sub component we want to show in the bottomPanel

**Comment by sinisarudan** [comment]
@mprinc: with this we have 10 closed issues in this milestone :)

**Comment by mprinc** [comment]
@sinisarudan Ih ten?! :)
