### ISSUE TITLE
Server ports Inacessible

### ISSUE THREAD

**Issue by sinisarudan** [mprinc/KnAllEdge#194]
1. many proxies (at public venues) forbid accessing to specific ports used by our CF server
2. So, workshop and CF usage becomes disabled

**Two services on the same port**
- [how to put nodejs and apache in the same port 80](http://stackoverflow.com/questions/11172351/how-to-put-nodejs-and-apache-in-the-same-port-80#comment38690958_11174042)
- [node-http-proxy](https://github.com/nodejitsu/node-http-proxy)
- [Combining Node.js & Apache](http://eastmond.org/blog/?p=45)

**Redirecting port**:
- [Best practices when running Node.js with port 80 (Ubuntu / Linode) [closed]](http://stackoverflow.com/questions/16573668/best-practices-when-running-node-js-with-port-80-ubuntu-linode)
- [Binding a Node.js App to Port 80 with Nginx](https://eladnava.com/binding-nodejs-port-80-using-nginx/)
- [Node.js in Production](http://blog.carbonfive.com/2014/06/02/node-js-in-production/)

**node-http-proxy**
- [github](https://github.com/nodejitsu/node-http-proxy)
- [tomeast/conditional-url-forwarding.js](https://gist.github.com/tomeast/952924)

# Solutions

## Apache forwarding

+ Apache listens on port 80
+ based on domain name we can redirect to node (backend on http://api.knalledge.org) or stay on Apache (frontend http://knalledge.org) or to topichat service (http://topichat.knalledge.org).
+ we need to install additional modules and configure
+ pros:
  + it makes node slower to follow Apache more inert architecture
+ cons:
  + it might more straightforward, since we already have Apache

## Nginx
+ Install Nginx proxy
+ config it and let it direct each subdomain (or maybe even path) to different ports
+ we need to move Apache from 80 to another port
+ pros
  + dedicated frontend dispatcher
  + efficient
  + longterm smart option
+ cons
  + might be difficult to install although probably not

## node-http-proxy
+ https://github.com/nodejitsu/node-http-proxy
+ similar to Nginx, but we need to add iptables forwarding rule for node-http-proxy to avoid running it as a root to be able to access the port 80
+ pros
  + more familiar procedure with detailed instructions
+ cons
  + not pro solution?
  + we need to keep it alive?

**Comment by sinisarudan** [comment]
http://stackoverflow.com/questions/11172351/how-to-put-nodejs-and-apache-in-the-same-port-80#comment38690958_11174042

**Comment by mprinc** [comment]
Fixed :D

**Comment by sinisarudan** [comment]
@mprinc OOOOOMMMMMMMMM !
