### ISSUE TITLE
Delete confirmation

### ISSUE THREAD

**Issue by mprinc** [mprinc/KnAllEdge#57]
Delete confirmation?! this halo icon could easily be clicked by an accident

mapVisualization.js:line 104:deleteNode

**Comment by sinisarudan** [comment]
Done. But still, we are allowing CTRL + Del to go uncomfirmed?!

**Comment by mprinc** [comment]
I think that is OK, since shortcut is much harder to trigger. In any case you can put confirmation in that.mapInteraction.deleteNode() and then it will be always asked

**Comment by sinisarudan** [comment]
ok, we want faster shortcuts actions. THus in the future, we sould add it to settings (if we want to have confirmation on shortcuts deleting or to ask user after first confirmation would he avoid this confirmation in future)
