### ISSUE TITLE
mapa ima po 5-6 primeraka moga id u participants, verovatno visestruki login link klik to izaziva

### ISSUE THREAD

**Issue by mprinc** [mprinc/KnAllEdge#59]
Here is the code that deals with adding logged user: `src/frontend/app/components/knalledgeMap/js/services.js`:line 1368

**Comment by sinisarudan** [comment]
@mprinc : you must provide function or code sample, because the code lines have changed drastically from the moment you wrote this?!

**Comment by sinisarudan** [comment]
Found in 'loadAndProcessData: function'

// Add active user to the map
					// ToDo: this is
					if(RimaService){
						var activeUserId = RimaService.getActiveUserId();
						if(activeUserId &&
							kMap.participants.indexOf(activeUserId) <= 0
						){

**problem is that this is array of ObjectId(ID).. and not of IDs**

Will fix it after this code becomes accessible due to MapVOService == undefined bug

**Comment by sinisarudan** [comment]
closed through my commit
