### ISSUE TITLE
`image-nodes` are covering other nodes

### ISSUE THREAD

**Issue by mprinc** [mprinc/KnAllEdge#65]
You can develop this algorithm for positioning nodes?

**Comment by sinisarudan** [comment]
how? we have no time now for this approach! maybe later, now we need something faster, a workaround

**Comment by mprinc** [comment]
OK. Then we can either put it on aside same as node text, or make a little icon of image to notify there is an image and when icon is clicked, image will be shown, and that icon can be a thumbnail of the image

**Comment by mprinc** [comment]
Fixed at the moment with providing thumbnail image support + clicking on thumbnail opens image in popup
