### ISSUE TITLE
UI buttons not working occasionally, until refreshed (e.g. _Button for hiding topPanel_ often doesn't work, while Settings button works?!)

### ISSUE THREAD

**Issue by mprinc** [mprinc/KnAllEdge#68]
For now, you can make a simple replacement with HTML button and I can try to figure out a reason

**Comment by sinisarudan** [comment]
caused by
https://github.com/mprinc/KnAllEdge/issues/75

Check why _settings (gear) button_ keeps working while identical topPanel OFF/ON, is affected by this $digest bug!!

P.S. here we talk about Angular Material switches

**Comment by mprinc** [comment]
closed with #02c4898

**Comment by mprinc** [comment]
closed with #02c4898
