### ISSUE TITLE
switches often (even working) don't change their state!

### ISSUE THREAD

**Issue by mprinc** [mprinc/KnAllEdge#70]
Same, try to find HTML checkbox replacement, and I will try to figure out when I have time

I suggest that you make a config parameter that will enable one or another component, so we can change mode for production and for development. That would be for all angular-material critical components

**Comment by sinisarudan** [comment]
caused by
https://github.com/mprinc/KnAllEdge/issues/75
P.S. here we talk about Angular Material switches

**Comment by sinisarudan** [comment]
caused by
https://github.com/mprinc/KnAllEdge/issues/75
P.S. here we talk about Angular Material switches

**Comment by mprinc** [comment]
Closed with 02c4898
