### ISSUE TITLE
node.name editing changes are lost (all that we typed) if we click somewhere on a node while editing

### ISSUE THREAD

**Issue by mprinc** [mprinc/KnAllEdge#76]
if during editing I click on the map, changes are saved.
But they are lost if I click on any other node or somewhere else on current/editing node, but outside of a input text field

**Comment by sinisarudan** [comment]
Not. Test it again!
Edit node.name, then click somewhere on its rights part, outside the text input field and all you typed is lost

**Comment by mprinc** [comment]
Closed by 09d0a89
