### ISSUE TITLE
node.name editing lost upon structural changes of other users

### ISSUE THREAD

**Issue by sinisarudan** [mprinc/KnAllEdge#78]
when **user1 is editing a node.name** and during that user2 (it happens in both cases of user2 being a presenter and not being) **does some change** (edits some node or creates or deeletes a node; votes); it happens that user1's map is refreshed by user2's change. User1 is kept in his node in edit status, but **all the changes are lost** and he is positioned back at the beginning of node.name, no matter where he was before user2's change

**Comment by mprinc** [comment]
**Disable**

+ filtering: show/hide ibis, ontov, reduction of visible nodes

**Provide**
+ remembering typed in text and position and restoring it
  + remember on any type, but what about updating? Increment + final
+ keep node positioned: either at the exact same position or at least visible
