### ISSUE TITLE
filtering messages per map

### ISSUE THREAD

**Issue by sinisarudan** [mprinc/KnAllEdge#80]
knAllEdgeRealTimeService must:
1. enhance broadcaasted messages with mapId
2. check in filterBroadcasting if the map is same as ours

**Comment by sinisarudan** [comment]
we introduced sessionID for filtering that will support in the future several sessions over the same map

**Comment by sinisarudan** [comment]
solve problem with backend deepassign module, how to integrate it and our fix in it for null values

**Comment by sinisarudan** [comment]
@mprinc : When you finish this backend ingetration on server, close this issue

**Comment by sinisarudan** [comment]
@mprinc : Have you integrated deep-assign on server so that this can be closed?

**Comment by mprinc** [comment]
not-sure anymore, i guess I did but better resend me zip by email again

**Comment by mprinc** [comment]
not-sure anymore, i guess I did but better resend me zip by email again

**Comment by sinisarudan** [comment]
sent to email. Confirm and close.
can be tested by creation of new map and seeing if it is created and accessible with visible rootNode and without crash of server

**Comment by mprinc** [comment]
Reupdated, restarted server, tested, works fine with creation without crashing and shows node in the map
